name: SCC

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - name: Lint
        run: cargo clippy --all
      - name: Format
        run: cargo fmt --all
      - name: Doc
        run: cargo doc --document-private-items
      - name: Miri
        run: rustup toolchain add nightly; rustup component add rust-src --toolchain nightly; rustup component add miri --toolchain nightly; cargo +nightly miri test --lib --bins --tests
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v2
      - name: Debug
        run: RUST_BACKTRACE=1 cargo test --verbose -- --nocapture
      - name: Debug(serde)
        run: RUST_BACKTRACE=1 cargo test serde --verbose --features serde
      - name: Release
        run: RUST_BACKTRACE=1 cargo test --release --verbose -- --nocapture
      - name: Release(serde) - Test
        run: RUST_BACKTRACE=1 cargo test --release serde --verbose --features serde
  benchmark:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - name: Release - Benchmark
        run: cargo bench
